spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springbatch?characterEncoding=UTF-8
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource

config:
  classpath: log4j2.yml


# 下面是配置undertow作为服务器的参数
undertow:
  # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
  io-threads: 4
  # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
  worker-threads: 20
  # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
  # 每块buffer的空间大小,越小的空间被利用越充分
  buffer-size: 1024
  # 是否分配的直接内存
  direct-buffers: true


---

# 开发配置
spring:
  profiles: dev
server:
  port: 8080
---

#测试环境配置
spring:
  profiles: test

server:
  port: 1001


---
#生产环境配置
spring:

  profiles: prd

server:
  port: 1002





